### ISSUE TITLE
units for `gsw.density.rho`?

### ISSUE THREAD

**Issue by davjfish** [TEOS-10/GSW-Python#178]
I'm wondering if there is a mistake in the docs with respect to the unit for `gsw.density.rho`. Should it be kg/m^3 instead of kg/m?

![image](https://github.com/user-attachments/assets/86194540-a411-4d09-8c55-fbbe52bcb91f)

**Comment by efiring** [comment]
You are correct.  The information in the docstrings, including these units, are taken from a Matlab version, so that is the origin of this error.  We will look into getting it fixed.  I don't know whether the error is still present in the latest Matlab version; since it is not developed using revision control we will need to check the latest zipfile.
